party_house/accounts/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path('signup/', views.SignUp.as_view(), name='signup'),
]

party_house/party/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.index, name='index'),
    path('profile/', views.PartyListView.as_view(), name='party-list-view'),
    path('party-details/<int:pk>', views.PartyDetailView.as_view(), name='party-information-detail'),
    path('RSVP/<int:user_id>/<str:creator>/<int:id>', views.PartyRSVPView),
]

from django.contrib.auth.decorators import login_required

urlpatterns += [
    path('party/create/', login_required(views.PartyCreate.as_view()), name='party_create'),
]

party_house/party_house/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('party/', include('party.urls')),
    path('', RedirectView.as_view(url='/party/', permanent=True)),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

party_house/accounts/models.py
from django.db import models

# Create your models here.

party_house/party/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from datetime import date

class PartyInformation(models.Model):
    address_st = models.CharField(max_length=100, help_text="Enter the street name for the party", blank=False)
    address_num = models.IntegerField(help_text="Enter the house address number, if none leave blank", blank=False)
    address_apt_num = models.CharField(max_length = 5, blank=True)
    address_zip = models.IntegerField(help_text="Enter the zip for the address", blank=False)
    address_city = models.CharField(max_length = 100, blank=False)
    description = models.CharField(max_length=750, help_text="Enter a description of the party (750 max characters!)", blank=False)
    date_of_party = models.DateField('Party Date', blank=False)
    active = models.BooleanField(help_text="Is the party active?", blank=False)
    creator = models.CharField(max_length=100, blank=False)

    def get_absolute_url(self):
        return reverse('party-information-detail', args=[str(self.id)])

    def __str__(self):
        return f'{self.address_zip}, {self.description}, {self.date_of_party}'

class Party(models.Model):
    party_information_id = models.ForeignKey(PartyInformation, on_delete=models.SET_NULL, null=True)
    party_thrower_id = models.ForeignKey(User, related_name='party_thrower_id', on_delete=models.SET_NULL, null=True)
    party_goer_id = models.ForeignKey(User, related_name = 'party_goer_id', on_delete=models.SET_NULL, null=True)
    applications = models.IntegerField(blank=True, default=1)
    status = models.IntegerField(default=1, help_text="1 for pending, 2 for accepted, 3 for rejected")
    attended=models.BooleanField(default=False)

    def get_absolute_url(self):
        return reverse('party-detail', args=[str(self.id)])

class Attended(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    num_attended = models.IntegerField(blank=True, help_text="Number of parties that you've attended")
    num_thumbs = models.IntegerField(blank=True, help_text="Number of thumbs that you have")

    def get_absolute_url(self):
        return reverse('attended', args=[str(self.id)])

    def __str__(self):
        return f'{self.num_attended}, {self.num_thumbs}'

class Testimonial(models.Model):
    party_id = models.ForeignKey('Party', on_delete=models.SET_NULL, null=True)
    user_id = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    thumbs = models.BooleanField()
    description = models.CharField(max_length=750, help_text="How was this person?", blank=False)

    def get_absolute_url(self):
        return reverse('testimonial', args=[str(self.id)])

    def __str__(self):
        return f'{self.thumbs}, {self.description}'

party_house/accounts/views.py
from django.shortcuts import render

from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views import generic


class SignUp(generic.CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'signup.html'

party_house/party/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.mixins import PermissionRequiredMixin
from .models import Party, PartyInformation, Testimonial
from django.views import generic
from django.contrib.auth.models import User

def index(request):
    all_parties = PartyInformation.objects.filter(active = 'True')

    return render(
        request,
        'index.html',
        context=
        {
            'all_parties':all_parties,
        }
    )

class PartyListView(generic.ListView):
    model = User
    context_object_name = 'my_party_list'
    queryset = PartyInformation.objects.all()
    template_name = '/partyinformation_list'
    def get_context_data(self, **kwargs):
        context = super(PartyListView, self).get_context_data(**kwargs)
        context['thumbs'] = User.objects.filter(attended__user = self.request.user)
        context['your_active_going_parties'] = PartyInformation.objects.filter(active = 'True').filter(party__status = 2).filter(party__party_goer_id = self.request.user.id)
        context['your_old_going_parties'] = PartyInformation.objects.filter(active = 'False').filter(party__status = 2).filter(party__party_goer_id = self.request.user.id)
        context['your_active_created_parties'] = PartyInformation.objects.filter(active = 'True').filter(party__party_thrower_id = self.request.user.id)
        context['your_old_created_parties'] = PartyInformation.objects.filter(active = 'False').filter(party__party_thrower_id = self.request.user.id)
        context['your_active_pending_parties'] = PartyInformation.objects.filter(active = 'True').filter(party__status = 1).filter(party__party_goer_id = self.request.user.id)
        context['your_active_rejected_parties'] = PartyInformation.objects.filter(active = 'False').filter(party__status = 3).filter(party__party_goer_id = self.request.user.id)
        context['your_active_parties_attended'] = PartyInformation.objects.filter(active = 'True').filter(party__status = 2).filter(party__party_goer_id = self.request.user.id).filter(party__attended = True)
        context['your_old_parties_attended'] = PartyInformation.objects.filter(active = 'False').filter(party__party_goer_id = self.request.user.id).filter(party__status = 2).filter(party__attended = True)
        context['your_old_parties_not_attended'] = PartyInformation.objects.filter(active = 'False').filter(party__party_goer_id = self.request.user.id).filter(party__status = 2).filter(party__attended = False)
        return context

from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from .models import PartyInformation

class PartyCreate(generic.CreateView):
    model = PartyInformation
    fields = [
    'address_st', 'address_num', 'address_apt_num', 'address_zip', 'address_city', 'description', 'date_of_party', 'creator', 'active']
    success_url = reverse_lazy('index')

from django.views import generic

class PartyDetailView(generic.DetailView):
    model = PartyInformation
    template_name = 'party/partyinformation_detail.html'

    def get_context_data(self, **kwargs):
        context = super(PartyDetailView, self).get_context_data(**kwargs)
        context['party_thrower_id'] = PartyInformation.creator
        context['party_information_id'] = PartyInformation.id
        return context

def PartyRSVPView(request, user_id, creator, id):
    party = Party()
    pinfo = PartyInformation.objects.get(id=id)
    uinfo = User.objects.get(id=user_id)
    creator = User.objects.get(id=creator)
    Party.objects.create(party_information_id=pinfo, party_thrower_id=creator, party_goer_id=uinfo)
    party.save()
    return render(request, 'index.html')

party_house/party/templates/base_generic.html
<!DOCTYPE html>
<html lang="en">
<head>

  {% block title %}<title>House Party III</title>{% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <link href="https://fonts.googleapis.com/css?family=Bangers|Open+Sans" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

  <!-- Add additional CSS in static file -->
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>

<body>

  <header>
    <div class="container clearfix">
      <div class= "navbar-wrapper">
          <div class="container">
              <nav class = "navbar navbar-inverse navbar-fixed-top" id="navbar_whole">

                      <div class = "navbar-header">
                          <button type= "button" class = "navbar-toggle collapsed" data-toggle = "collapse" data-target= "#navbar" aria-expanded="false" aria-controls = "navbar">
                              <span class="sr-only"></span>
                              <span class="icon-bar"></span>
                              <span class="icon-bar"></span>
                              <span class="icon-bar"></span>
                          </button>
                          <!--Below is the top-left hand side of the screen where you usually see a company/project name and a logo-->
                          <!--The next line sends the user back to the home page-->
                          <a class="navbar-brand" href="{%url 'index' %}">
                              <!--Insert the file name of your brand image below after the 'img'-->
                               <img class="img-responsive" src="/static/images/house_party_iii_logo_white2.png">
                          </a>
                      </div>

                      <div id= "navbar" class="navbar-collapse collapse">
                          <ul class="nav navbar-nav">
                            <!--Below is where you put the rest of the links to the pages you've created. Please reference your own models
                             in Django.-->
                              <li class="navbar-font">
                                  <a href="{% url 'index' %}">Home</a>
                              </li>
                              <li class="navbar-font">
                                  <a href="">Parties</a>
                              </li>
                          </ul>
                      <div id= "navbar" class="navbar-collapse collapse">
                          <ul id="navigation-right" class="nav navbar-nav navbar-right">
                              {% if user.is_authenticated %}
                              <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Account <span class="caret"></span></a>
                                <ul class="dropdown-menu">
                                  <li class="navbar-font"><a href="">My Parties</a></li>

                                    <li class="navbar-font">
                                        <a href="{% url 'party_create' %}">Throw a Party</a>
                                    </li>

                                  <li role="separator" class="divider"></li>
                                  <li id="username-nav" class="dropdown-header">{{ user.get_username }}</li>
                                  <li class="navbar-font"><a href="{% url 'party-list-view' %}">Profile</a></li>
                                  <li class="navbar-font"><a href="{% url 'logout'%}?next={{request.path}}">Logout</a></li>
                                </ul>
                              </li>
                              {% else %}
                                <li class="navbar-font"><a href="{% url 'login'%}?next={{request.path}}">Login</a></li>
                                <li class="navbar-font"><a href="{% url 'login'%}?next={{request.path}}">Signup</a></li>
                              {% endif %}
                          </ul>
                      </div>
              </nav>
          </div>
      </div>
    </div>
  </header>
  {% block content %} {% endblock %}<br><br>
  <footer class="footer navbar-fixed-bottom">
    <div class= "navbar navbar-inverse navbar-static-bottom" role="navigation">
        <div class="navbar-text pull-left">
        </div>
        <div class="navbar-text pull-left">
        &copy; A Casey & Hani Joint, 2018
        </div>
    </div>
    </footer>
    <script type="text/javascript">
      function startButton() {
        document.getElementById("start-button").style.display="none";
        document.getElementById("party-index").style.visibility="visible";
      }
    </script>
</body>
</html>

party_house/party/templates/index.html
{% extends "base_generic.html" %}
{% load bootstrap3 %}

{% block content %}
<img id="title-logo" src="/static/images/house_party_iii_logo_800x600.png">
<h4 class="font-type">Connecting people to the parties and parties to the people</h3>
<br><br>
{% if all_parties %}

<button id="start-button" type="submit" value="Submit" class="btn btn-lg btn-primary" onclick="startButton()">Let's get started!</button>

<div id="party-index" class="row">
  <div class="col-xs-3"></div>
  	<div class="col-xs-6 well">
  		<ul>
	  {% for party in all_parties %}
	    <li class="font-type"><a href="{{ party.get_absolute_url }}">{{ party }}</a></li>
	  {% endfor %}
	  </ul>
	</div>
  <div class="col-xs-3"></div>
</div>

  {% endif %}
{% endblock %}

party_house/party/templates/party/partyinformation_detail.html
{% extends "base_generic.html" %}

{% block content %}
  <br><br>
  <h1>{{ partyinformation.creator }}'s Party</h1>

  <p><strong>Address: </strong><br>{{partyinformation.address_num}} {{partyinformation.address_st}}<br>{{partyinformation.address_city}} {{partyinformation.address_zip}}</a></p>
  <p><strong>Description: </strong><br>{{ partyinformation.description }}</p>
  <p><strong>Date: </strong><br> {{ partyinformation.date_of_party }}</p>

  <h2>Wanna go? There's X spots left! RSVP here: </h2>
  <a href="/party/RSVP/{{user.id}}/{{partyinformation.creator}}/{{partyinformation.id}}">Let's do it!</a>

{% endblock %}

party_house/party/templates/party/partyinformation_form.html
{% extends "base_generic.html" %}

{% block content %}
<br><br>
<h1>Where's the party?</h1><br>

<form action="" method="post">
    {% csrf_token %}
  <table>
    <tr>
      <th>
        <label for="id_address_st">Address st:</label>
      </th>
      <td>
        <input type="text" name="address_st" maxlength="100" required id="id_address_st">
        <br>
        <span class="helptext">Enter the street name for the party</span>
      </td>
    </tr>
    <tr>
      <th>
        <label for="id_address_num">Enter the address number:</label>
      </th>
      <td>
      <input type="number" name="address_num" required id="id_address_num">
        <br>
        <span class="helptext">Enter the address number</span>
      </td>
    </tr>
    <tr>
      <th>
        <label for="id_address_apt_num">Address apartment num:</label>
      </th>
      <td>
        <input type="text" name="address_apt_num" maxlength="5" required="" id="id_address_st">
        <br>
        <span class="helptext">Enter the address apartment num (if none leave blank)</span>
      </td>
    </tr>
    <tr>
      <th>
        <label for="id_address_zip">Zip code:</label>
      </th>
      <td>
        <input type="number" name="address_zip" required id="id_address_zip">
        <br>
        <span class="helptext">Enter the zip code</span>
      </td>
    </tr>
    <tr>
      <th>
        <label for="id_address_city">City: </label>
      </th>
      <td>
        <input type="text" name="address_city" maxlength="100" required id="id_address_city">
        <br>
        <span class="helptext">Enter the city: </span>
      </td>
    </tr>
    <tr>
      <th>
        <label for="id_description">Description of party: </label>
      </th>
      <td>
        <input type="text" name="description" maxlength="750" required id="id_description">
        <br>
        <span class="helptext">Enter the description of the party</span>
      </td>
    </tr>
    <tr>
      <th>
        <label for="id_date_of_party">Party date: </label>
      </th>
      <td>
        <input type="text" name="date_of_party" required id="id_date_of_party">
        <br>
        <span class="helptext">Party date: </span>
      </td>
    </tr>
    <tr>
      <td>
        <input type="hidden" name="creator" required  id="id_creator" value={{user.username}}>
        <br>
      </td>
    </tr>
    <tr>
      <th>
        <label for="id_active">Active: </label>
      </th>
      <td>
        <input type="checkbox" name="active" required= id="id_active">
        <br>
        <span class="helptext">Is the party happening?</span>
      </td>
    </tr>
  </table>
  <input type="submit" value="Submit" />
</form>
{% endblock %}

party_house/party/templates/party/partyinformation_list.html
{% extends "base_generic.html" %}

{% block content %}
{{ user }}
<br><br>
  <h1>PROFILE PAGE</h1>
  {% if thumbs %}
    {% for thumb in thumbs %}
      <p>Number of thumbs: {{ thumbs }}</p>
    {% endfor %}
  {% else %}
    <p>You haven't gotten any thumbs yet!</p>
  {% endif %}

  {% if your_active_going_parties %}
    {% for party in your_active_going_parties %}
      <p>Upcoming Party: {{ party }}</p>
    {% endfor %}
  {% else %}
    <p>You're not going to any parties!</p>
  {% endif %}

  {% if your_old_going_parties %}
    {% for party in your_old_going_parties %}
      <p>Old Party: {{ party }} </p>
    {% endfor %}
  {% else %}
    <p>You don't have any old parties!</p>
  {% endif %}

  {% if your_active_created_parties %}
    {% for party in your_active_created_parties %}
      <p>Your Created Party: {{ party }} </p>
    {% endfor %}
  {% else %}
    <p>You're not throwing any parties!</p>
  {% endif %}

  {% if your_old_created_parties %}
    {% for party in your_old_created_parties %}
      <p>Your old created parties: {{ party }} </p>
    {% endfor %}
  {% else %}
    <p>You don't have any old created parties!</p>
  {% endif %}

  {% if your_active_pending_parties %}
    {% for party in your_active_pending_parties %}
      <p>Your active pending parties: {{ party }} </p>
    {% endfor %}
  {% else %}
    <p>You don't have any active pending parties!</p>
  {% endif %}

  {% if your_active_rejected_parties %}
    {% for party in your_active_rejected_parties %}
      <p>Your active rejected parties: {{ party }} </p>
    {% endfor %}
  {% else %}
    <p>You don't have any active rejected parties!</p>
  {% endif %}

  {% if your_active_parties_attended %}
    {% for party in your_active_parties_attended %}
      <p>Your active attended parties: {{ party }} </p>
    {% endfor %}
  {% else %}
    <p>You don't have any active attended parties!</p>
  {% endif %}

  {% if your_old_parties_attended %}
    {% for party in your_old_parties_attended %}
      <p>Your old attended parties: {{ party }} </p>
    {% endfor %}
  {% else %}
    <p>You don't have any old attended parties!</p>
  {% endif %}

  {% if your_old_parties_not_attended %}
    {% for party in your_old_parties_not_attended %}
      <p>Your old NOT attended parties: {{ party }} </p>
    {% endfor %}
  {% else %}
    <p>You don't have any old NOT attended parties!</p>
  {% endif %}

{% endblock %}

party_house/party/templates/signup.html
{% extends "base_generic.html" %}

{% block title %}Sign Up{% endblock %}

{% block content %}
  <h2>Sign up</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Sign up</button>
  </form>
{% endblock %}